### ISSUE TITLE
Euruko 2013 Web Site

### ISSUE THREAD

**Issue by bandito** [euruko2013/general#2]
I don't know if any decisions are made on this subject yet but we as Skroutz can support the design (and implementation if that's ok ) of the euruko 2013 official web site. 

In any case I think the design should start as quick as possible because it may take some time to nail it.

**Comment by cedel** [comment]
I agree with Bandito. I think it would be better if the site is handled by a team like the guys at Skroutz, instead of trying to coordinate people who work at different companies during the day.

**Comment by giedriusr** [comment]
Agree. There should be dedicated team/company which will take care of it rather than different people from different places.

**Comment by pagojo** [comment]
Sounds like a neat offer to me. That's the spirit:-) 

If the rest of the committee is game let's go for it. But we'll need to wait couple of days before it is final (yes/no). 

Beware though, since in our last meeting we said I'll handle the public communications, Skroutz (or anyone else) will have to deal at least with myself as far as the content of the site goes...

btw we also said we'd like to keep it hosted on GitHub

is the offer still on :-P?

**Comment by petros** [comment]
:+1: for Skroutz's offer by me. Also yea, having all assets (source code) on GitHub will help keep everything in one place. However, if the site needs dynamic features, we cannot deploy it as GitHub Pages. We may need Heroku or a similar solution.

**Comment by pagojo** [comment]
(flame proof jacket on) we can always do CORS (flame proof jacket off)

btw as far as the Logo goes, I think we MUST have a competition, it is more fun :-)

**Comment by teoulas** [comment]
:+1:

Even if we need a dynamic site, we would still keep all code here and deploy on Heroku. No problems here. :)

**Comment by stream7** [comment]
:+1:

@pagojo regarding the logo competition, we could contact some design teams to see if there is interest around this. e.g. https://twitter.com/#!/DesignWalk

**Comment by pagojo** [comment]
@stream7 well tell everybody :-)

**Comment by damphyr** [comment]
I've already put a bit of a blurb on how to respond to calls for contributions on the README in [general](https://github.com/euruko2013/general) and I'll put up a bit of directory structure like this
   logo/template/README.md
   logo/template/logo.svg
   logo/template/log.png
and then we can accept pull requests from potential candidates. We use the pull request discussion to vote and discuss the proposals.

**Comment by damphyr** [comment]
And in case a designer is not so GitHub savvy as we want anyone should feel free to act as a proxy by posting a pull request on his/her behalf

**Comment by pagojo** [comment]
sure go for it, I have someone in mind to send it to ;-)

**Comment by bandito** [comment]
@pagojo offer still on :P

As to where it will be hosted, dynamic vs static, github vs heroku etc, I think it's a bit early to tell. We have some ideas but it all boils down to what the community thinks it's better and will serve the purpose.

**Comment by fotos** [comment]
Can't :thumbsup: Skroutz, even tho I'd love too ([COI](http://en.wikipedia.org/wiki/Conflict_of_interest))! :smile:

Nevertheless I also believe that the design of the website should be handled by a single organization / entity / company. Whoever eventually does the design, the process should be **transparent** and **open**, to both criticism and ideas. Thus hosting the source code of the design / website on GitHub is crucial. The design should come out in lots of small iterations, instead of in one big step, as it will be easier to see the progress and gather feedback. As far as website hosting goes, that depends on both the technologies used and the know-how of the deployer.

I also support the idea of @damphyr and @pagojo for an open logo competition. Either way we'll need a (short) design brief and some guidelines to give to prospective designers. What are your thoughts on the incentive (e.g bragging rights, thank you mention at the end of the conference, 1 year subscription to [SmashingMagazine](http://www.smashingmagazine.com/))?

Going over [past](http://2009.euruko.org) [years](http://euruko2010.org) [Euruko](http://euruko2011.org) [websites](http://euruko2012.org), most have the following sections:
1. Agenda - Schedule
2. Venue
3. Speakers
4. Visitors / Traveller Info 
5. Sponsors
6. Supporters / Volunteers
7. Blog for news / updates

What are the milestones for the website? By August a first rough cut and by the end of September or early October, a full fleshed out website?

**Comment by pagojo** [comment]
@fotos excuse my naivete but where is the conflict of interest for Skroutz?

As for the rest, your points have been taken and we will address them in the committee and come back, transparently of course :-)

**Comment by fotos** [comment]
@pagojo well... I shouldn't vote for the company I work for!

Sure, let's get the party started! :D

**Comment by pagojo** [comment]
ahh right got it ! I thought you said it was dubious for Skroutz to offer to do the site.  

As for the site design
a) I feel we should try and host all of it on GitHub (can't see why not, or why we'd like 'dynamic' features)
b) all the code _must_ be hosted on GitHub.

Now what I think should be on this site are (in no particular order):
1. Call for presentations (and ref to GitHub area)
2. Call for Sponsors / sponsors
3. Venue and dates (when available) or candidate dates for now
4. How to obtain tickets (when ready)
5. Organising committee with small bios
6. Speakers with bios (when ready)
7. Traveller Info (when ready)
8. Info for spouses and or parallel programmes/activities (if/when ready or as they come along)
9. Supporters / Volunteers with mini bios) or at least links to their sites/twitter etc)
10. Link to this GitHub area
11. Call for logo competition
12. Media brief and ref to Twitter accounts, fora, FB etc
13. News section?
14. Call for contribution, support etc
15. Programme (when ready)

All of the above can be accommodated exclusively on GitHub at no extra cost btw :-)

thoughts?

**Comment by giedriusr** [comment]
What about mobile app as AMS had this year? Apart of that, list looks great. I'd love to add some kind of fun part section, where we could post how we are organizing stuff: pics, videos, etc..
I will try to make a video from this year Euruko and how Athens won the voting (so this could go into that section). Sorry, was really busy and couldn't make it earlier.

**Comment by damphyr** [comment]
There are some neat ideas for a mobile app that go somewhat further than what AMS had this year. More on it at the athens.rb Meetup as it's one of the "surprises" we have in store.

**Comment by nikosd** [comment]
definitely a :+1: from me :)

**Comment by pagojo** [comment]
@bandito Offer accepted by the organising committee, skroutz to develop the EuRuKo 2013 website :-)

Still we have to finalise the spec without too much feature creeping :o) give us few days for hat as well please.
Would also be nice if you can meet us on the 20th of July at the Athens Ruby Meetup.

**Comment by giedriusr** [comment]
@pagojo it's Euruko 2013, not 2012 :P

**Comment by bandito** [comment]
Great. We'll be there to discuss the details.
